config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, {
    path: 'auth',
    controllers: {
      registrations: :custom_registrations
    },
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
    }
  }

  resources :contacts, except: [:show] do
    get 'autocomplete', on: :collection
  end

  get '/dashboard', to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  self.table_name  = 'contacts'
  self.primary_key = 'id'

  paginates_per 3

  has_attached_file :avatar, styles: { medium: "150x150>", thumb: "100x100" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  belongs_to :group
  belongs_to :user

  validates :name, :email, :group_id, presence: true
  validates :name, length: { minimum: 2 }

  def get_avatar
    avatar = (avatar.present? ) ? avatar.url.present(:thumb) : gravatar
  end

  def gravatar
    hash = Digest::MD5.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{hash}"
  end
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  self.table_name  =  'groups'
  self.primary_key =  'id'

  default_scope -> { order(:name) }

  has_many :contacts, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  self.table_name  = 'users'
  self.primary_key = 'id'

  has_many :groups, dependent: :destroy
  has_many :contacts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  add_flash_types :success, :warning, :danger, :info
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized 
  rescue_from ActiveRecord::RecordNotFound, with: :show_404

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || dashboard_path
  end
  
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  private

  def user_not_authorized
    flash[:danger] = 'You are not authorized to perform this action.'
    redirect_to action: :index
  end

  def show_404
    render template: 'errors/404', status: 404
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end 
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:edit, :update, :destroy]

  def index
    if (params[:group_id] && !params[:group_id].empty?)
      @contacts = current_user.contacts.where(group_id: params[:group_id]).
        order(created_at: :desc).page(params[:page])
    else
      @contacts = current_user.contacts.page(params[:page]).
        order(created_at: :desc)
    end
  end

  def autocomplete
    @contacts = Contact.search(params[:term]).
      order(created_at: :desc).
        page(params[:page])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = current_user.contacts.build(contact_params)
    if @contact.save
      flash[:success] = "Contact was successfuly created."
      redirect_to contacts_path
    else
      flash[:error] = "Contact failed to be created."
      render 'new'
    end
  end

  def edit
    authorize @contact
  end

  def update
    authorize @contact
    if @contact.update(contact_params)
      flash[:success] = "Contact was successfully updated."
      redirect_to contacts_path
    else
      flash[:error] = "Contact failed to be updated."
      render :edit
    end
  end

  def destroy
    authorize @contact
    @contact.destroy
    flash[:success] = "Contact was successfully deleted."
    redirect_to contacts_path
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact)
      .permit(:name, :company, :email, :phone, :address, :group_id, :avatar)
  end
end 

app/controllers/custom_registrations_controller.rb
# frozen_string_literal: true

class CustomRegistrationsController < Devise::RegistrationsController
  protected

  def after_update_path_for(resource)
    edit_user_registration_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupController < ApplicationController
  def index
    @group = current_user.groups.build(group_parmas)
    if @group.save
      render json: @group, status: :created
    else
      render json: @group.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_registrations_helper.rb
module CustomRegistrationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_contact.html.erb
<tr>
  <td class="middle">
    <div class="media">
      <div class="media-left">
        <%= link_to contact_path(contact) do %>
          <%= image_tag(contact.get_avatar, class: 'media-object',
            style: 'width: 100px; height: 100px;') %>
        <% end %>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= contact.name %></h4> 
        <address>
          <strong><%= contact.company %></strong><br>
          <%= contact.email %>
        </address>
        <span class='badge' style='margin-top: -20px;'><%= contact.group.name %></span>
      </div>
    </div>
  </td>
  <td width="100" class="middle">
    <div>
      <%= link_to edit_contact_path(contact), 
        class: 'btn btn-circle btn-default btn-xs', title: 'Edit'  do %>
        <i class="glyphicon glyphicon-edit"></i>
      <% end %>
      
      <%= link_to contact_path(contact), 
        class: 'btn btn-circle btn-danger btn-xs', title: 'Remove', method: :delete do %>
        <i class="glyphicon glyphicon-remove"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/contacts/_form.html.erb
  <div class="panel panel-default">

    <%= form_for(@contact, html: { multipart: true }) do |f| %>
      <div class="panel-body">
      <div class="form-horizontal">
        <div class="row">
          <div class="col-md-8">
          
            <div class="form-group">
              <%= f.label :name, 'Name', class: 'control-label col-md-3' %>
              <div class="col-md-8">
                <%= f.text_field :name, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :company, 'Company', class: 'control-label col-md-3' %>
              <div class="col-md-8">
                <%= f.text_field :company, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :email, 'E-mail', class: 'control-label col-md-3' %>
              <div class="col-md-8">
                <%= f.email_field :email, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :phone, 'Phone', class: 'control-label col-md-3' %>
              <div class="col-md-8">
                <%= f.text_field :phone, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :address, 'Address', class: 'control-label col-md-3' %>
              <div class="col-md-8">
                <%= f.text_area :address, class: 'form-control', rows: 3 %>
              </div>
            </div>
            <div class="form-group">
              <label for="group" class="control-label col-md-3">Group</label>
              <div class="col-md-5">
                <%= f.collection_select(:group_id, current_user.groups, :id, :name,
                {prompt: 'Select group'}, class: 'form-control') %>
              </div>
              <div class="col-md-3">
                <a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
              </div>
            </div>
            <div class="form-group" id="add-new-group">
              <div class="col-md-offset-3 col-md-8">
                <div class="input-group">
                  <input type="text" name="new_group" id="new_group" class="form-control">
                  <span class="input-group-btn">
                    <a href="#" class="btn btn-default">
                      <i class="glyphicon glyphicon-ok"></i>
                    </a>
                  </span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="fileinput fileinput-new" data-provides="fileinput">
              <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;">
                <%= image_tag @contact.get_avatar, alt: 'Photo',
                  style: 'width: 150px; height: 150px;' %>
              </div>
              <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
              <div class="text-center">
                <span class="btn btn-default btn-file"><span class="fileinput-new">Choose Photo</span><span class="fileinput-exists">Change</span>
                  <%= f.file_field :avatar %>
                </span>
                <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
      <div class="panel-footer">
      <div class="row">
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <%= f.submit 'Save', class: 'btn btn-primary' %>
              <%= link_to contacts_path, class: 'btn btn-default' do %>
                Cancel
              <% end %>
            </div>
          </div>
        </div>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/contacts/edit.html.erb
<div class='col-md-offset-2 col-md-8'>
  <div class='panel panel-default'>
    <div class='panel-heading'>
      <strong>Edit Contact</strong>
    </div>

    <%= render 'form' %>
  </div>
</div>

app/views/contacts/index.html.erb
<% if @contacts.blank? %>
<div class='alert alert-warning'>
  <strong>Record not found</strong>
</div>
<% end %>


<!-- sidebar -->
<div class='col-md-3'>
  <%= render 'layouts/sidebar' %>
  
  <div class='row'>
    <div class='col-md-12'>
      <div class='alert alert-info'>
        <span>Created by: </span>
        <h5 class='bold'>Renato Rosa Franco</span>
      </div>
    </div>
  </div>
</div>

<!-- yield --->
<div class='col-md-9'>

    <div class="panel panel-default">
      <div class='panel-heading clearfix'>
        <div class='pull-left'>
          <h4>All Contacts</h4>
        </div>

        <div class='pull-right'>
          <%= link_to  new_contact_path, class: 'btn btn-success' do %>
            <i class='glyphicon glyphicon-plus'></i>
            Add Contact
          <% end %>
        </div>
      </div>

      <table class="table">
        <% @contacts.each do |contact| %>
          <%= render 'contact', contact: contact %>
        <% end %>
      </table>            
    </div>

    <div class="text-center">
      <%= paginate(@contacts) if !@contacts.empty? %>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class='col-md-offset-2 col-md-8'>
  <div class='panel panel-default'>
    <div class='panel-heading'>
      <strong>Add Contact</strong>
    </div>

    <%= render 'form' %>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class='col-md-10 col-md-offset-1'>
  <div class='jumbotron text-center'>
    <h2>Hello <%= current_user.name %></h2>
    <p class='lead'>Welcome to Contact Manager App.</p>

    <p>
      <%= link_to "Manage Contacts", contacts_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>

app/views/home/index.html.erb
<div class='col-md-10 col-md-offset-1'>
  <div class='jumbotron text-center'>
    <h1>Free Online Contact Manager</h1>
    <p>Organize your contacts free and easly.</p>

    <p>
      <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-primary btn-lg' %>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-default btn-lg' %>
    </p>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% unless flash.empty? %>
  <script>
    <% flash.each do |type, message| %>
    <%= type = type.to_s.gsub('alert', 'error').gsub('notice', 'info') %>
    toastr["<%= type %>"]("<%= message %>", "<%= type.upcase %>");
    <% end %>
  </script>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" 
         data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to root_path, class: 'navbar-brand text-uppercase' do %>
          My Contact
        <% end %>
      </div>

      <!-- /.navbar-header -->
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class='nav navbar-nav'>
        <% if current_user %>
          <li class='active'><%= link_to 'Dashboard', dashboard_path %></li>
        <% end %>
          <li class='#'><%= link_to 'All Contacts', contacts_path %></li>
        </ul> 

        <div class='navbar-right'>
        <% if !current_user %>
          <%= link_to new_user_session_path, 
            class: 'btn btn-default navbar-btn' do %>
              Login
          <% end %>
          <%= link_to new_user_registration_path, 
            class: 'btn btn-primary navbar-btn' do %>
              Register
          <% end %>
        </div>
        <% else %>
        <div class='nav navbar-right navbar-nav'>
          <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fas fa-user-circle"></i>
            <%= current_user.name %></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Logout',  destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% end %>
        </div>
      <% end %> 
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <%= content_tag :div, message, class: "alert alert-#{type}" %>
<% end %>   

app/views/layouts/_sidebar.html.erb
<div class="list-group">
  <% active = params[:group_id].eql?(nil) || params[:group_id].empty? ? 'active' : '' %>
  <%= link_to contacts_path, class: "list-group-item #{active}" do %>
    All Contact
    <span class='badge'> <%= current_user.contacts.count %> </span>
  <% end %>
  <% current_user.groups.each do |group| %>
    <% active = params[:group_id].to_i == group.id ? 'active' : '' %>
    <%= link_to contacts_path(group_id: group.id), class: "list-group-item #{active}" do %>
      <%= group.name %> 
      <span class='badge'><%= group.contacts.count %></span>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='pt-BR'>
  <head>
    <title>Contact Manager - <%= yield :title %> </title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/5165849ba2.js" crossorigin="anonymous"></script>
  </head>
  <body class="<%= controller.controller_name %>" data-spy='scroll'>
    <!-- header -->
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_messages' %>

    <!-- content -->
    <div class='container'>
      <div class='row'>
        <%= yield  %>
      </div>
    </div>

    <!-- footer -->
    <%= render 'layouts/footer' %>
  </body>
</html>